language: node_js

node_js:
  - "node"

services:
  - docker

#sudo: false
#before_install:
#  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
#  - export PATH=$HOME/.yarn/bin:$PATH
#cache:
#  yarn: true

cache: yarn

install:
  - yarn

jobs:
  include:
    - stage: lint
      script: yarn lint
    - stage: test 
      script: yarn test
      deploy:
        provider: script
        script: ./deploy.sh
        on:
      branch: master
